### PR TITLE
Revert email patch for p2o

### PR DESCRIPTION
**Pull request by obaroikoh**

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
Please build a new SDS image via (from the repo directory):

- Build Grimoire base image: `cd docker-images/base/ && docker login (as dajohn) && DOCKER_USER=dajohn ./build_minimal.sh && cd ../../`.
- Build SDS images: `DOCKER_USER=dajohn ./docker-images/build-validate.sh && DOCKER_USER=dajohn BRANCH=test ./docker-images/build.sh && DOCKER_USER=dajohn BRANCH=prod ./docker-images/build.sh`.

Thanks

**Comment by lukaszgryglicki** [comment]
New SDS generated.

**Comment by obaroikoh** [comment]
Thanks

**Pull request merged**
