### PR TITLE
Da 2600 Tloc

### PR DESCRIPTION
**Pull request by lfpratik**
get total lines of code from all git source

### CODE REVIEW

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm but I would like to have one more review and then let me know if I should build a new SDS with this and just enable it?

**Review by code-sleuth — APPROVED** [review]
lgtm

**Comment by code-sleuth** [comment]
@lukaszgryglicki yes, go ahead and build a new sds image.

**Comment by lukaszgryglicki** [comment]
OK then, now building a new image. I'll let you know when all is built.

**Comment by code-sleuth** [comment]
Sure, thanks Lukas

**Comment by lukaszgryglicki** [comment]
Was it tested?
The build failed and I needed to fix wrong file names: https://github.com/LF-Engineering/sync-data-sources/commit/01540768b4581143d1a54f34f300944b88f5fd2e

**Comment by lukaszgryglicki** [comment]
The base image built OK after that small fix - tested - p2o.py works from within.
Now I will build an SDS image.

**Comment by lukaszgryglicki** [comment]
OK new SDS build, it will run in the next sync.

**Comment by lukaszgryglicki** [comment]
New SDS with git LOC support added is running now. You can monitor it, check git repos data, etc on `ec2prod`.
To monitor progress ssh to `ec2prod` and:
```
docker container ls
clear; tail -f /tmp/sds-prod-main.log
```

To see git repos/clones data examine:
`/root/.perceval/`, `/data/` directories.

**Comment by lukaszgryglicki** [comment]
I see error messages like:
```
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master

Traceback (most recent call last):
  File "/repos/grimoirelab-elk/grimoire_elk/elk.py", line 163, in feed_backend
    last_update = ocean_backend.feed(**params)
  File "/repos/grimoirelab-elk/grimoire_elk/raw/elastic.py", line 228, in feed
    self.feed_items(items)
  File "/repos/grimoirelab-elk/grimoire_elk/raw/elastic.py", line 245, in feed_items
    for item in items:
  File "/repos/grimoirelab-perceval/perceval/backend.py", line 226, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/repos/grimoirelab-perceval/perceval/backends/core/git.py", line 162, in fetch_items
    latest_items, no_update)
  File "/repos/grimoirelab-perceval/perceval/backends/core/git.py", line 275, in __fetch_from_repo
    repo = self.__create_git_repository()
  File "/repos/grimoirelab-perceval/perceval/backends/core/git.py", line 326, in __create_git_repository
    self.git_loc.load()
  File "/repos/grimoirelab-perceval/perceval/utils.py", line 460, in load
    self._pull()
  File "/repos/grimoirelab-perceval/perceval/utils.py", line 434, in _pull
    self._exec(cmd, env=env)
  File "/repos/grimoirelab-perceval/perceval/utils.py", line 339, in _exec
    raise RepositoryError(cause=cause)
perceval.errors.RepositoryError: git command - There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master


2020-09-08 08:14:00,089 [git] Done collection for https://gerrit.tungsten.io/r/tungstenfabric/windows-docker-driver
2020-09-08 08:14:00,090 Backend feed completed
```
This may be related to this PR IMHO - is it fatal, or is it just preventing LOC analysis, or is it unrelated? I think this should be investigated, we should always fall back to "do nothing" when LOC analysis fails due to any reason and then continue normally.
cc @lfpratik @code-sleuth @1010sachin

**Comment by lfpratik** [comment]
@lukaszgryglicki, It is a command error, raised new PR https://github.com/LF-Engineering/sync-data-sources/pull/19

**Pull request merged**
