### PR TITLE
Da 3166

### PR DESCRIPTION
**Pull request by lfpratik**
Add github pr reviewer fields to the github pr enriched index

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
Have you tried the full build workflow? - because recently build was filing after some PR was merged.
The full workflow is to start in SDS directory and then:
- `cd ./docker-images/base/`.
- ./collect_and_build.sh`.
- `docker build -f Dockerfile -t "dajohn/dev-analytics-grimoire-docker-minimal" .`.
- Do not push yet! Check if p2o.py works inside the image:
- `docker run -it "dajohn/dev-analytics-grimoire-docker-minimal" p2o.py`.
- If p2o.py works OK then:
- `docker push "dajohn/dev-analytics-grimoire-docker-minimal"`.
- When this is finished back to SDS main directory: `cd ../../`.
- Build the `validate` image: `DOCKER_USER=dajohn PRUNE=1 ./docker-images/build-validate.sh`.
- Build the `test` image: `DOCKER_USER=dajohn BRANCH=test PRUNE=1 ./docker-images/build.sh`.
- Check if it works OK: `SH=1 DBG=1 DRY=1 ./docker-images/run_sds.sh test` - this starts SDS in dry-run mode.
- While inside the SDS run: `/fetch.sh && syncdatasources`.
- Build the `prod` image (only when test image is tested and `test` SDS finished at least one normal sync): `DOCKER_USER=dajohn BRANCH=prod PRUNE=1 ./docker-images/build.sh`.
- Check if it works OK: `SH=1 DBG=1 DRY=1 ./docker-images/run_sds.sh prod` - this starts SDS in dry-run mode.
- While inside the SDS run: `/fetch.sh && syncdatasources`.

This is all described [here](https://github.com/LF-Engineering/sync-data-sources/blob/master/BUILD_IMAGES.md)

**Comment by lfpratik** [comment]
@lukaszgryglicki, I am able to build an image but it fails while running the SDS command. 

`Traceback (most recent call last):
  File "/usr/local/bin/p2o.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/repos/grimoirelab-elk/utils/p2o.py", line 27, in <module>
    from grimoire_elk.elk import feed_backend, enrich_backend
  File "/usr/local/lib/python3.7/dist-packages/grimoire_elk/elk.py", line 35, in <module>
    from .utils import get_connectors, get_connector_from_name, get_elastic
  File "/usr/local/lib/python3.7/dist-packages/grimoire_elk/utils.py", line 79, in <module>
    from perceval.backends.weblate.weblate import Weblate, WeblateCommand
ModuleNotFoundError: No module named 'perceval.backends.weblate'
`
I am looking into this issue ... right now I don't have ETA for this

**Comment by lukaszgryglicki** [comment]
that's exactly what I'm talking about - and then next steps. This "grimoire" thing is really nasty and I have p2o errors so many times, even when I didn't change anything. They just change something upstream and their tool just stops working - also asked them many times that they should have a test coverage that ensures that full-stack is still working after updates - but this was never created. Why ever create so many test cases testing every single thing in the grimoire stack, while the entire tool is just broken and this is ignored?

**Comment by lfpratik** [comment]
@lukaszgryglicki, I can fix this with a patch for an emergency. I am thinking I can provide a good solution asap.

**Comment by lukaszgryglicki** [comment]
That's what we usually do - there is no other option. So please do and then confirm the next steps - until the SDS test image is built and you run`syncdatasources` in it successfully.

**Comment by lukaszgryglicki** [comment]
If you want to do it in a safe mode - replace `dajohn` with your own docker username.

**Comment by lukaszgryglicki** [comment]
I just wanted to merge this but unfortunatelly:
```
2020-12-24 07:07:24 root@teststats:~/dev/go/src/github.com/LF-Engineering/sync-data-sources/docker-images/base# ./collect_and_build.sh
Cloning into 'grimoirelab-perceval'...
remote: Enumerating objects: 35, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 10017 (delta 6), reused 25 (delta 6), pack-reused 9982
Receiving objects: 100% (10017/10017), 3.21 MiB | 5.60 MiB/s, done.
Resolving deltas: 100% (7420/7420), done.
Cloning into 'grimoirelab-elk'...
remote: Enumerating objects: 16418, done.
remote: Total 16418 (delta 0), reused 0 (delta 0), pack-reused 16418
Receiving objects: 100% (16418/16418), 5.27 MiB | 7.02 MiB/s, done.
Resolving deltas: 100% (12632/12632), done.
Cloning into 'grimoirelab-sortinghat'...
remote: Enumerating objects: 109, done.
remote: Counting objects: 100% (109/109), done.
remote: Compressing objects: 100% (62/62), done.
remote: Total 7237 (delta 55), reused 76 (delta 38), pack-reused 7128
Receiving objects: 100% (7237/7237), 2.19 MiB | 4.64 MiB/s, done.
Resolving deltas: 100% (5254/5254), done.
Cloning into 'grimoirelab-kingarthur'...
remote: Enumerating objects: 154, done.
remote: Counting objects: 100% (154/154), done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 1377 (delta 101), reused 125 (delta 77), pack-reused 1223
Receiving objects: 100% (1377/1377), 387.50 KiB | 1.18 MiB/s, done.
Resolving deltas: 100% (949/949), done.
Cloning into 'cloc'...
remote: Enumerating objects: 4160, done.
remote: Total 4160 (delta 0), reused 0 (delta 0), pack-reused 4160
Receiving objects: 100% (4160/4160), 3.10 MiB | 5.54 MiB/s, done.
Resolving deltas: 100% (2374/2374), done.
Note: checking out 'a4f9037d2a7f69406a8eabdc0e3553f093b254e9'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 5 (delta 3), reused 3 (delta 3), pack-reused 2
Unpacking objects: 100% (5/5), done.
From https://github.com/chaoss/grimoirelab-perceval
 * [new ref]         refs/pull/680/head -> slack-history-api-revert
Switched to branch 'slack-history-api-revert'
First, rewinding head to replay your work on top of it...
Applying: Revert "[slack] Use channels.history to retrieve message"
Using index info to reconstruct a base tree...
M	perceval/backends/core/slack.py
M	tests/test_slack.py
Falling back to patching base and 3-way merge...
Auto-merging tests/test_slack.py
Auto-merging perceval/backends/core/slack.py
CONFLICT (content): Merge conflict in perceval/backends/core/slack.py
error: Failed to merge in the changes.
Patch failed at 0001 Revert "[slack] Use channels.history to retrieve message"
Use 'git am --show-current-patch' to see the failed patch

Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".

./collect_and_build.sh: line 27: cd: grimoirelab-elk: No such file or directory
./collect_and_build.sh: line 32: cd: grimoirelab-sortinghat: No such file or directory
```

**Comment by lukaszgryglicki** [comment]
I think we no longer need this because da-ds GHA will contain PR reviewer fields that will come from GHA not from p2o.py that gets them from GitHub API.
cc @lfpratik @1010sachin

**Pull request closed without merging**
