### PR TITLE
Disable dockerhub dads in prod

### PR DESCRIPTION
**Pull request by khalifapro**

### CODE REVIEW

**Review by 1010sachin — APPROVED** [review]
lgtm

**Comment by lukaszgryglicki** [comment]
Should I build a new `prod` SDS image? Are all `auth0` problems gone?  need a green light @1010sachin @khalifapro @fayazg ...

**Comment by khalifapro** [comment]
this pr is not related to auth0, it's for disable docker hub-dads

**Comment by lukaszgryglicki** [comment]
But the new SDS build will use a new `auth0` lib so this is why I'm asking.

**Comment by khalifapro** [comment]
That's fine!

**Comment by lukaszgryglicki** [comment]
OK, building.

**Pull request merged**
