### PR TITLE
Da 3378

### PR DESCRIPTION
**Pull request by lfpratik**
Following PR hold the following points.

1. Fixed the grimoire labs stack building issue
2. Fixed the dependency installation of grimoire labs stack
3. Updated patches with  grimoire labs upstream to avoid the runtime issues
4. Added the addition logs for LOC
5. Added the LOC cache as Fallback to avoid the 0 Lines of code.
6. Did the optimization on ELK patches to speedup the p2o.py

**Note:** above fixes solved the total loc issues.  We can run the QA cycle in a test environment.

### CODE REVIEW

**Comment by 1010sachin** [comment]
@lfpratik I am seeing some issues especially with sds-cloud-foundry-cloud-foundry-git index where the commit_url that is set as a part of https://jira.linuxfoundation.org/browse/DA-2635 is not getting set correctly. It is adding the repo_url in the commit_url field. Can it be related to this change?

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm
But please note two things:
1) When `da-ds` git is enabled (on test or prod) p2o.py won't run. I remember that `da-ds` already used some code from python patches, but that was probably related to LOC, so once we switch to da-ds git we must make sure it works the same. But please remember that *anything* we added/patched to `p2o.py` since the new da-ds git/GitHub implementation was made (a month ago or a bit more) - will have to be re-done in `da-ds` as well.
2) There were also patches for GitHub ds (pull_request reviewers data) - note that `test` already uses `da-ds-gha` (GitHub archives) so any patching of GitHub reviewer data makes no sense for `test` and will only apply to `prod` (but only till a moment where p2o.py GitHub is replaced with `da-ds-gha`).
3) @1010sachin any changes from this PR cannot have an effect on anything that is in cloud-foundry now, because this PR wasn't merged and deployed yet.

**Comment by lfpratik** [comment]
@lukaszgryglicki, as I know GitHub pr reviewers stats done from the da-ds me @code-sleuth was doing some more investigation like how much information we can get ... Same we can pull it from the da-ds ...

**Comment by lukaszgryglicki** [comment]
OK, I'm building the image for the test now. Fort GitHub da-ds we use GitHub archives - it's different from GitHub API, we just get reviewers authors daa.

**Comment by lukaszgryglicki** [comment]
`test` looks OK... please ping me if you want to apply this for `prod` as well.
cc @1010sachin @fayazg @lfpratik

**Comment by lfpratik** [comment]
@lukaszgryglicki, I am ok to go on production if test ok

**Pull request merged**
