### PR TITLE
Add dockerhub org support

### PR DESCRIPTION
**Pull request by teragopher**

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
And after you merge, please follow [this](https://github.com/LF-Engineering/sync-data-sources/pull/8#issuecomment-665178104).

Thanks.

**Comment by teragopher** [comment]
@lukaszgryglicki yes tested. Sample results here https://jira.linuxfoundation.org/browse/DA-2359

**Comment by lukaszgryglicki** [comment]
Great! PR using this should follow on DA-api repo.

**Comment by lukaszgryglicki** [comment]
New SDS generated.

**Pull request merged**
