### PR TITLE
Da 2600 tloc

### PR DESCRIPTION
**Pull request by lfpratik**

### CODE REVIEW

**Review by code-sleuth — APPROVED** [review]
lgtm

**Comment by lukaszgryglicki** [comment]
Generated a new SDS based on that.
Next SDS sync will use it.

**Comment by lukaszgryglicki** [comment]
Seems like a new `p2o.py` (after merging this PR) is broken:
```
Digest: sha256:1886c670ed724b6124ee4d60d5ff7ee4f1d1cba7dfcf9acfa2b310b472268f52
Status: Downloaded newer image for dajohn/sync-data-sources-test:latest
docker.io/dajohn/sync-data-sources-test:latest
Your branch is up-to-date with 'origin/test'.
Already up-to-date.
2020-09-14 06:00:36: STDERR:
Traceback (most recent call last):
  File "/usr/local/bin/p2o.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/repos/grimoirelab-elk/utils/p2o.py", line 27, in <module>
    from grimoire_elk.elk import feed_backend, enrich_backend
  File "/repos/grimoirelab-elk/grimoire_elk/elk.py", line 35, in <module>
    from .utils import get_connectors, get_connector_from_name, get_elastic
  File "/repos/grimoirelab-elk/grimoire_elk/utils.py", line 68, in <module>
    from perceval.backends.core.rss import RSS, RSSCommand
  File "/repos/grimoirelab-perceval/perceval/backends/core/rss.py", line 29, in <module>
    import feedparser
  File "/usr/local/lib/python3.5/dist-packages/feedparser/__init__.py", line 31, in <module>
    from .api import parse
  File "/usr/local/lib/python3.5/dist-packages/feedparser/api.py", line 56, in <module>
    from . import http
  File "/usr/local/lib/python3.5/dist-packages/feedparser/http.py", line 156
    new_pieces[1] = f'{url_pieces.hostname}:{url_pieces.port}'
                                                             ^
SyntaxError: invalid syntax

2020-09-14 06:00:36: Command, arguments, environment:
[p2o.py --help]
map[]
Command and arguments:
[p2o.py --help]
map[]
2020-09-14 06:00:36: Error(time=2020-09-14 06:00:36.058605661 +0000 UTC m=+1.606114339):
Error: 'exit status 1'
Stacktrace:
goroutine 1 [running]:
runtime/debug.Stack(0xc0000daca0, 0xc0001f8050, 0xd)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/LF-Engineering/sync-data-sources/sources.FatalOnError(0xaefc40, 0xc0000daca0, 0x2, 0x2)
	/go/src/github.com/LF-Engineering/sync-data-sources/sources/error.go:14 +0xc8
github.com/LF-Engineering/sync-data-sources/sources.ExecCommand(0xc000106840, 0xc00000c060, 0x2, 0x2, 0x0, 0x0, 0x1a, 0x10, 0x0, 0x0)
	/go/src/github.com/LF-Engineering/sync-data-sources/sources/exec.go:161 +0xb2e
main.ensureGrimoireStackAvail(0xc000106840, 0x0, 0x0)
	/go/src/github.com/LF-Engineering/sync-data-sources/sources/cmd/syncdatasources/syncdatasources.go:74 +0x56f
main.main()
	/go/src/github.com/LF-Engineering/sync-data-sources/sources/cmd/syncdatasources/syncdatasources.go:6077 +0xdc
```

cc @lfpratik @1010sachin

**Comment by lfpratik** [comment]
@lukaszgryglicki, Thanks for the update, it looks like port is missing for feed parsers. Let me check which SDS command is executed and breaks the enrichment.

**Comment by lukaszgryglicki** [comment]
Sure, `p2o.py` command line is constructed [here](https://github.com/LF-Engineering/sync-data-sources/blob/master/sources/cmd/syncdatasources/syncdatasources.go#L5581).

**Comment by lfpratik** [comment]
@lukaszgryglicki , New PR https://github.com/LF-Engineering/sync-data-sources/pull/26

**Pull request merged**
